# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: site
          image: ghcr.io/ibnumasud/ibnumasud.github.io:1d59f30d59e426b3694974df1f12466b1a3e1402
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi